# Generated by Django 4.1.5 on 2023-01-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_clothes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.FloatField(),
        ),
    ]
